version: "3"

services:
    web1:
        image: dockercloud/website
        container_name: nginx
        ports:
            - "81:80"

    web2:
        image: dockercloud/website
        container_name: sachinkuber/new-nginx
        ports:
            - "82:80"

    haproxy:
        build: ./haproxy
        container_name: haproxy
        ports:
            - "80:80"
